image: condaforge/miniforge3

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive
  ADIMU_CONDA_FEEDSTOCK_PATH: conda-recipe/adimu-feedstock
  ADIMU_PKG_NAME: adimu

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
  only:
    - master
    - add_uart
  script:
    - 'apt-get update && apt-get install -y --no-install-recommends cmake build-essential git vim gcc-aarch64-linux-gnu g++-aarch64-linux-gnu'
    - 'export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu/'
    - 'conda config --set custom_channels.garage-conda-local https://artifactory.analog.com/artifactory'
    - 'conda create -n tmu-build -c garage-conda-local -c conda-forge -y conda-build conda-verify garconda'
    - 'source activate tmu-build'
    - 'export TMU_VERSION=`cat VERSION`'
    - 'conda build -c garage-conda-local -c conda-forge --output-folder conda-output/ $ADIMU_CONDA_FEEDSTOCK_PATH'
    - 'ls conda-output/linux-*/$CONDA_PKG_NAME-*'
  artifacts:
    paths:
      - conda-output/linux-64/$ADIMU_PKG_NAME-*
      - conda-output/linux-aarch64/$ADIMU_PKG_NAME-*
    expire_in: 3 hrs

deploy_x86_64:
  stage: deploy
  tags:
    - docker
  only:
    - tags
  dependencies:
    - build
  script:
    - 'apt-get update && apt-get install -y --no-install-recommends curl'
    # - 'TAG=`git describe --tags --abbrev=0 | sed -E "s/v*(.*)/\1/g"`; if [[ $TAG != $TMU_VERSION ]]; then echo -e "TAG($TAG) and VERSION($TMU_VERSION) mismatch. Packaging skipped."; exit 1; fi'
    - 'curl https://artifactory.analog.com/artifactory/garage-conda-local/linux-64/$(basename conda-output/linux-64/$ADIMU_PKG_NAME-*) -I'
    - 'if [[ $? == 0 ]]; then echo "Package already available in artifactory. Exiting."; exit 1; fi;'
    - 'curl -X PUT --fail https://artifactory.analog.com/artifactory/garage-conda-local/linux-64/$(basename conda-output/linux-64/$ADIMU_PKG_NAME-*) -T $(realpath conda-output/linux-64/$ADIMU_PKG_NAME-*)'

deploy_aarch64:
  stage: deploy
  tags:
    - docker
  only:
    - tags
  dependencies:
    - build
  script:
    - 'apt-get update && apt-get install -y --no-install-recommends curl'
    # - 'TAG=`git describe --tags --abbrev=0 | sed -E "s/v*(.*)/\1/g"`; if [[ $TAG != $TMU_VERSION ]]; then echo -e "TAG($TAG) and VERSION($TMU_VERSION) mismatch. Packaging skipped."; exit 1; fi'
    - 'curl https://artifactory.analog.com/artifactory/garage-conda-local/linux-aarch64/$(basename conda-output/linux-aarch64/$ADIMU_PKG_NAME-*) -I'
    - 'if [[ $? == 0 ]]; then echo "Package already available in artifactory. Exiting."; exit 1; fi;'
    - 'curl -X PUT --fail https://artifactory.analog.com/artifactory/garage-conda-local/linux-aarch64/$(basename conda-output/linux-aarch64/$ADIMU_PKG_NAME-*) -T $(realpath conda-output/linux-aarch64/$ADIMU_PKG_NAME-*)'

